DSO-3729: Fix missing default branch

diff --git a/actions/generic-store-version-as-list-config-in-git/action.yml b/actions/generic-store-version-as-list-config-in-git/action.yml
--- a/actions/generic-store-version-as-list-config-in-git/action.yml
+++ b/actions/generic-store-version-as-list-config-in-git/action.yml
@@ -63,10 +63,6 @@ runs:
         if [[ "${{ inputs.enable-auto-filter-target-ref }}" == "true" ]]; then
           # Extract the base of the branch name (e.g., "hotfix-base/25.1")
           TARGET_FILTER_BRANCH_VERSION=$(echo "${{ inputs.target-repo-ref }}" | sed -E 's|([0-9]+\.[0-9]+)\.[0-9]+$|\1|' | sed -E 's|refs/heads/||')
-          if [[ -z "${TARGET_FILTER_BRANCH_VERSION}" ]]; then
-            echo "[ERROR] Unable to get filter pattern from [${{ inputs.target-repo-ref }}]"
-            exit 1
-          fi
           echo "Searching for branches in ${{ inputs.target-repo }} containing: $TARGET_FILTER_BRANCH_VERSION"
 
           # Use the GitHub API to list branches that match the filter
@@ -99,30 +95,41 @@ runs:
         else
           TARGET_BRANCH=$(echo ${{ inputs.target-repo-ref }} | sed -E 's|refs/heads/||')
           # The `jq` utility is used to parse the JSON response
-          BRANCHES=$(curl -s -H "Authorization: token ${{ inputs.pat-token }}" \
+          DEFAULT_BRANCH=$(curl -s -H "Authorization: token ${{ inputs.pat-token }}" \
             -H "Accept: application/vnd.github.v3+json" \
-            "https://api.github.com/repos/${{ inputs.target-repo }}/branches" | \
-            jq -r --arg filter "$TARGET_BRANCH" '[.[] | .name | select(. == $filter)]')
-          # Count the number of branches found
-          BRANCH_COUNT=$(echo "$BRANCHES" | jq 'length')
-          echo "Found $BRANCH_COUNT matching [$TARGET_BRANCH]."
+            "https://api.github.com/repos/${{ inputs.target-repo }}" | \
+            jq -r '.default_branch')
 
-          # Check if more than one branch was found. This should not happen!!
-          if [[ "$BRANCH_COUNT" -gt 1 ]]; then
-            echo "[Error] More than one branch found matching [$TARGET_BRANCH]."
-            echo "Found branches: $(echo "$BRANCHES" | jq -r '. | join(", ")')"
-            exit 1
-          # Check if no branches were found
-          elif [[ "$BRANCH_COUNT" -eq 0 ]]; then
-            echo "[Error] No branches found matching [$TARGET_BRANCH]."
-            exit 1
-          # Exactly one branch was found
+          if [[ "$TARGET_BRANCH" == "$DEFAULT_BRANCH" && -n "$TARGET_BRANCH" ]]; then
+            echo "[INFO] Matching default branch [$TARGET_BRANCH] on target repo"
           else
-            BRANCH_NAME=$(echo "$BRANCHES" | jq -r '.[0]')
-            echo "[INFO] Successfully found branch [$TARGET_BRANCH] at target repo."
+            # The `jq` utility is used to parse the JSON response
+            BRANCHES=$(curl -s -H "Authorization: token ${{ inputs.pat-token }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/${{ inputs.target-repo }}/branches" | \
+              jq -r --arg filter "$TARGET_BRANCH" '[.[] | .name | select(. == $filter)]')
+            # Count the number of branches found
+            BRANCH_COUNT=$(echo "$BRANCHES" | jq 'length')
+            echo "Found $BRANCH_COUNT matching [$TARGET_BRANCH]."
+
+            # Check if more than one branch was found. This should not happen!!
+            if [[ "$BRANCH_COUNT" -gt 1 ]]; then
+              echo "[Error] More than one branch found matching [$TARGET_BRANCH]."
+              echo "Found branches: $(echo "$BRANCHES" | jq -r '. | join(", ")')"
+              exit 1
+            # Check if no branches were found
+            elif [[ "$BRANCH_COUNT" -eq 0 ]]; then
+              echo "[Error] No branches found matching [$TARGET_BRANCH]."
+              exit 1
+            # Exactly one branch was found
+            else
+              BRANCH_NAME=$(echo "$BRANCHES" | jq -r '.[0]')
+              echo "[INFO] Successfully found branch [$TARGET_BRANCH] at target repo."
+            fi
           fi
+          
           # Set the output for other jobs to use
-          echo "branch-ref=${{ inputs.target-repo-ref }}" >| tee -a $GITHUB_OUTPUT
+          echo "branch-ref=${{ inputs.target-repo-ref }}" | tee -a $GITHUB_OUTPUT
         fi
 
     - uses: actions/checkout@v4
