DSO-32 Fix var name

diff --git a/actions/generic-check-if-artifact-already-promoted/action.yml b/actions/generic-check-if-artifact-already-promoted/action.yml
--- a/actions/generic-check-if-artifact-already-promoted/action.yml
+++ b/actions/generic-check-if-artifact-already-promoted/action.yml
@@ -30,20 +30,50 @@ runs:
       env:
         JF_ENV_1: ${{ inputs.jfrog-token }}
 
-    - name: Check for source properties
+    - name: Check if source and target is identical
       id: get-properties
       env:
+        SRC_ARTIFACT_PROP_JSON_FILE: src-artifact-prop-file
         RELEASE_ARTIFACT_PROP_JSON_FILE: release-artifact-prop-file
       run: |
         set +e
+        ## Check for source first
+        validResult='false'
+        srcSha256Checksum=''
+        ${{ github.action_path }}/../../scripts/generic-curl-get-artifact-meta.sh \
+            "${{ inputs.source-artifact-full-path }}" \
+            "" \
+            "${{ env.SRC_ARTIFACT_PROP_JSON_FILE }}"
+        if [[ $? -eq 0 ]]; then
+            srcSha256Checksum=$(cat ${{ env.SRC_ARTIFACT_PROP_JSON_FILE }} | jq -r ".checksums.sha256")
+            echo SRC_ARTIFACT_SHA256=${srcSha256Checksum}
+            echo SRC_ARTIFACT_SHA256=${srcSha256Checksum} >> $GITHUB_ENV
+        else
+            echo "[ERROR] Unable to find source artifact: ${{ inputs.source-artifact-full-path }}"
+            exit 1
+        fi
+
+        ## Check for target release version
         validResult='false'
         ${{ github.action_path }}/../../scripts/generic-curl-get-artifact-meta.sh \
             "${{ inputs.source-artifact-full-path }}" \
-            "properties" \
+            "" \
             "${{ env.RELEASE_ARTIFACT_PROP_JSON_FILE }}"
         if [[ $? -eq 0 ]]; then
-            validResult='true'
+            releaseSha256Checksum=$(cat ${{ env.RELEASE_ARTIFACT_PROP_JSON_FILE }} | jq -r ".checksums.sha256")
+            echo RELEASE_ARTIFACT_SHA256=${releaseSha256Checksum}
+            echo RELEASE_ARTIFACT_SHA256=${releaseSha256Checksum} >> $GITHUB_ENV
+            if [[ "$srcSha256Checksum" == "$releaseSha256Checksum" ]]; then
+                validResult='true'
+            else
+                echo "[ERROR] SHA256 comparison of source and target release are different. Few posibilities - old base code needs to be rebase or release artifactory has been overwritten."
+                echo "[DEBUG] SRC_ARTIFACT_SHA256=[$srcSha256Checksum], RELEASE_ARTIFACT_SHA256=[releaseSha256Checksum]"
+                exit 1
+            fi
+        else
+            echo "[INFO] Unable to find source artifact: ${{ inputs.source-artifact-full-path }}"
         fi
+
         echo ::set-output name=valid-result::${validResult}
       shell: bash
 
